--Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2020.1 (win64) Build 2902540 Wed May 27 19:54:49 MDT 2020
--Date        : Wed Jul 13 17:51:20 2022
--Host        : DESKTOP-DMI0M5P running 64-bit major release  (build 9200)
--Command     : generate_target edge_detection_ip.bd
--Design      : edge_detection_ip
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
